U6D5T4/Auctionify

src/Auctionify.API/Controllers/LotsController.cs
src/Auctionify.Application/Common/Behaviours/ValidationBehaviour.cs
src/Auctionify.Application/Features/Lots/Commands/Delete/DeleteLotCommand.cs
src/Auctionify.Application/Features/Lots/Commands/Delete/DeleteLotCommandValidator.cs
src/Auctionify.Application/Features/Lots/Commands/Delete/DeletedLotResponse.cs
src/Auctionify.Application/Features/Lots/Profiles/MappingProfiles.cs
src/Auctionify.Application/Features/Lots/Queries/GetAll/GetAllLotsQuery.cs
src/Auctionify.Application/Features/Lots/Queries/GetAll/GetAllLotsResponse.cs
src/Auctionify.Application/Features/Lots/Queries/GetById/GetByIdLotQuery.cs
src/Auctionify.Application/Features/Lots/Queries/GetById/GetByIdLotResponse.cs
src/Auctionify.Infrastructure/Persistence/ApplicationDbContextInitializer.cs

[NL-89 View lot profile (Backend)](https://jjbcapital.atlassian.net/browse/NL-89)
[NL-93 Remove the lot (Backend)](https://jjbcapital.atlassian.net/browse/NL-93)
Functionality to view lot profile
and Functionality to delete the lot
Created functionality to view lot profile and refactored the code (nlog setup, exception handling middleware, api info, rest api)
Auctionify.API:
- Auctionify.API.Controllers
- Auctionify.API.Middlewares
Auctionify.Application:
- Auctionify.Application.Common
- Auctionify.Application.Features
Auctionify.Core:
- Auctionify.Core.Enums
Auctionify.Infrastructure:
- Auctionify.Infrastructure.Repositories
_Build_
_Unit Tests_

[89] View lot profile (Backend), [93] Remove the lot (Backend)

---

src/Auctionify.API/Controllers/LotsController.cs
src/Auctionify.Application/Auctionify.Application.csproj
src/Auctionify.Application/Common/Interfaces/Repositories/IBidRepository.cs
src/Auctionify.Application/Common/Interfaces/Repositories/ILotRepository.cs
src/Auctionify.Application/Features/Lots/Commands/Delete/DeleteLotCommand.cs
src/Auctionify.Application/Features/Lots/Commands/Delete/DeletedLotResponse.cs
src/Auctionify.Application/Features/Lots/Commands/Update/UpdateLotCommand.cs
src/Auctionify.Application/Features/Lots/Commands/UpdateLotStatus/UpdateLotStatusCommand.cs
src/Auctionify.Application/Features/Lots/Commands/UpdateLotStatus/UpdateLotStatusCommandValidator.cs
src/Auctionify.Application/Features/Lots/Commands/UpdateLotStatus/UpdateLotStatusResponse.cs
src/Auctionify.Application/Features/Lots/Profiles/MappingProfiles.cs
src/Auctionify.Core/Enums/AuctionStatus.cs
src/Auctionify.Infrastructure/ConfigureServices.cs
src/Auctionify.Infrastructure/Persistence/ApplicationDbContextInitializer.cs
src/Auctionify.Infrastructure/Repositories/BidRepository.cs

[NL-87 Lot statuses (Backend)](https://jjbcapital.atlassian.net/browse/NL-87)
Update Endpoint for Lot Status changes for the specified lot (with validations)
The status of the lot can be changed using the UpdateLotStatus endpoint. The endpoint checks for the correct status changes, i.e. it has validations for status transformation.
Auctionify.API.Controllers
Auctionify.Applications.Features
Auctionfiy.Core.Enums
Auctionfiy.Infrastructure.Persistence.ApplicationDbContextInitializer.cs
_Build_

[87] - Lot statuses (Backend)

---

.github/workflows/dev_auctionify(dev).yml
src/Auctionify.API/Program.cs
src/Auctionify.API/appsettings.Development.json
src/Auctionify.Infrastructure/Identity/SendGridEmailService.cs

Add GitHub workflow file and changes in configuration 
Added Workflow file with migrations and tests
Auctionify.API
Auctionify.Infrastrucure
_Build_

[81] Deploy project to Azure

---

.github/workflows/dev_auctionify(dev).yml

[81] Workflow file fixes

---

src/Auctionify.API/Controllers/LotsController.cs
src/Auctionify.Application/Auctionify.Application.csproj
src/Auctionify.Application/Common/DTOs/GetListResponseDto.cs
src/Auctionify.Application/Common/DTOs/UserDto.cs
src/Auctionify.Application/Common/Models/Requests/PageRequest.cs
src/Auctionify.Application/Features/Lots/Profiles/MappingProfiles.cs
src/Auctionify.Application/Features/Lots/Queries/BaseQueryModels/GetAllLots.cs
src/Auctionify.Application/Features/Lots/Queries/GetAll/GetAllLotsQuery.cs
src/Auctionify.Application/Features/Lots/Queries/GetAll/GetAllLotsResponse.cs
src/Auctionify.Application/Features/Lots/Queries/GetAllByName/GetAllLotsByNameQuery.cs
src/Auctionify.Application/Features/Lots/Queries/GetAllByName/GetAllLotsByNameResponse.cs
src/Auctionify.Core/Auctionify.Core.csproj
src/Auctionify.Core/Persistence/Dynamic/DynamicQuery.cs
src/Auctionify.Core/Persistence/Dynamic/Filter.cs
src/Auctionify.Core/Persistence/Dynamic/IQueryableDynamicFilterExtensions.cs
src/Auctionify.Core/Persistence/Paging/BasePageableModel.cs
src/Auctionify.Core/Persistence/Paging/IPaginate.cs
src/Auctionify.Core/Persistence/Paging/IQueryablePaginateExtensions.cs
src/Auctionify.Core/Persistence/Paging/Paginate.cs
src/Auctionify.Core/Persistence/Repositories/EfBaseRepository.cs
src/Auctionify.Core/Persistence/Repositories/IAsyncRepository.cs
src/Auctionify.Infrastructure/Identity/IdentityService.cs

[NL-97 Search lots by name (Backend)](https://jjbcapital.atlassian.net/browse/NL-97)
Add GetAllLotsByNameQuery and corresponding controller
Implementation of lots search by name including query with handler and mappings. Also includes base implementations for pagination and filtration classes
Auctionify.API.Controllers
Auctionify.Application.Common.DTOs
Auctionify.Application.Features.Lots
Auctionify.Core.Persistance
_Build_

[97] - Search lots by name (Backend)

---

.github/workflows/dev_auctionify(dev).yml

[81] Worflow file fixes

---

src/Auctionify.Infrastructure/ConfigureServices.cs

[81] EnableRetryOnFailure (Connection to database)

---

.github/workflows/dev_auctionify(dev).yml

[81] GitHub Workflow file update

---

.github/workflows/dev_auctionify(dev).yml

[81] Update GitHub workflow file

---

src/Auctionify.API/ClientApp/angular.json

[81] Increasing budget

---

.github/workflows/dev_auctionify(dev).yml

[81] Dist file location fix

---

.github/workflows/dev_auctionify(dev).yml

[81] Creation of the folder wwwroot

---

.github/workflows/dev_auctionify(dev).yml

[NL-131 Update CI/CD to include Angular](https://jjbcapital.atlassian.net/browse/NL-131)
_Build_
_Unit Tests_

[131] Update CI/CD to include Angular

---

.github/workflows/dev_auctionify(dev).yml

[NL-131 Update CI/CD to include Angular](https://jjbcapital.atlassian.net/browse/NL-131)
_Build_
_Unit Tests_

[131] Ci/CD fix

---

src/Auctionify.API/Program.cs

[NL-131 Update CI/CD to include Angular](https://jjbcapital.atlassian.net/browse/NL-131)
_Build_
_Unit Tests_

[131] UseStaticFiles

---

.github/workflows/dotnet.yml

GitHub workflow for build and test solution
Auctionify
_Build_

GitHub workflow

---

.github/workflows/dev_auctionify(dev).yml

Dev fix (final)

---

src/Auctionify.API/ClientApp/angular.json
src/Auctionify.API/ClientApp/package-lock.json
src/Auctionify.API/ClientApp/package.json
src/Auctionify.API/ClientApp/src/app/app.module.ts
src/Auctionify.API/ClientApp/src/app/components/seller/components/dashboard-active-lots/dashboard-active-lots.component.html
src/Auctionify.API/ClientApp/src/app/components/seller/components/dashboard-active-lots/dashboard-active-lots.component.scss
src/Auctionify.API/ClientApp/src/app/components/seller/components/dashboard-active-lots/dashboard-active-lots.component.spec.ts
src/Auctionify.API/ClientApp/src/app/components/seller/components/dashboard-active-lots/dashboard-active-lots.component.ts
src/Auctionify.API/ClientApp/src/app/components/seller/dashboard/dashboard.component.html
src/Auctionify.API/ClientApp/src/app/components/seller/dashboard/dashboard.component.scss
src/Auctionify.API/ClientApp/src/app/components/seller/seller.module.ts
src/Auctionify.API/ClientApp/src/app/ui-elements/lot-item/lot-item.component.html
src/Auctionify.API/ClientApp/src/app/ui-elements/lot-item/lot-item.component.scss
src/Auctionify.API/ClientApp/src/app/ui-elements/lot-item/lot-item.component.spec.ts
src/Auctionify.API/ClientApp/src/app/ui-elements/lot-item/lot-item.component.ts
src/Auctionify.API/ClientApp/src/app/ui-elements/ui-elements.module.ts
src/Auctionify.API/ClientApp/src/app/web-api-client.ts
src/Auctionify.API/ClientApp/src/styles.scss
src/Auctionify.API/Controllers/LotsController.cs
src/Auctionify.Application/Features/Lots/Profiles/MappingProfiles.cs
src/Auctionify.Application/Features/Lots/Queries/GetAllActiveForSeller/GetAllActiveLotsForSellerQuery.cs
src/Auctionify.Application/Features/Lots/Queries/GetAllActiveForSeller/GetAllActiveLotsForSellerResponse.cs
src/Auctionify.Application/Features/Lots/Queries/GetAllLotsWithStatusForSeller/GetAllLotsWithStatusForSellerQuery.cs
src/Auctionify.Application/Features/Lots/Queries/GetAllLotsWithStatusForSeller/GetAllLotsWithStatusForSellerResponse.cs
tests/Auctionify.UnitTests/GetAllLotsWithStatusForSellerTests/GetAllLotsWithStatusForSellerQueryHandlerTests.cs

[NL-32 View active lots(seller)](https://jjbcapital.atlassian.net/browse/NL-32)
Implement active lots in seller's dashboard
Implement GetAllLotsWithStatusForSeller Query and handler, unit tests and design frontend part of the dashbord for corresponding functionality. Also added swiper.js
Auctionify.API.Controllers
Auctionify.API.Application
Auctionify.API.ClientApp
_Build_
_Unit Tests_

[NL-32] - View active lots(seller)

---

src/Auctionify.API/ClientApp/angular.json
src/Auctionify.API/ClientApp/src/app/components/buyer/buyer-routing.module.ts
src/Auctionify.API/ClientApp/src/app/components/buyer/buyer.module.ts
src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.html
src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.scss
src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.spec.ts
src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.ts
src/Auctionify.API/ClientApp/src/app/components/buyer/wishlist/wishlist.component.html
src/Auctionify.API/ClientApp/src/app/components/buyer/wishlist/wishlist.component.scss
src/Auctionify.API/ClientApp/src/app/components/buyer/wishlist/wishlist.component.spec.ts
src/Auctionify.API/ClientApp/src/app/components/buyer/wishlist/wishlist.component.ts
src/Auctionify.API/ClientApp/src/app/components/general/general.module.ts
src/Auctionify.API/ClientApp/src/app/components/general/home/auction/auction.component.ts
src/Auctionify.API/ClientApp/src/app/components/general/lot-profile/lot-profile.component.scss
src/Auctionify.API/ClientApp/src/app/components/general/lot-profile/lot-profile.component.ts
src/Auctionify.API/ClientApp/src/app/components/general/remove-from-watchlist/remove-from-watchlist.component.html
src/Auctionify.API/ClientApp/src/app/components/general/remove-from-watchlist/remove-from-watchlist.component.scss
src/Auctionify.API/ClientApp/src/app/components/general/remove-from-watchlist/remove-from-watchlist.component.spec.ts
src/Auctionify.API/ClientApp/src/app/components/general/remove-from-watchlist/remove-from-watchlist.component.ts
src/Auctionify.API/ClientApp/src/app/layout/header/header.component.html
src/Auctionify.API/ClientApp/src/app/layout/header/header.component.ts
src/Auctionify.API/ClientApp/src/app/layout/navbar-seller/navbar-seller.component.html
src/Auctionify.API/ClientApp/src/app/services/date-calculation/date-calculation.service.ts
src/Auctionify.API/ClientApp/src/app/web-api-client.ts
src/Auctionify.API/Program.cs
src/Auctionify.Application/Features/Users/Queries/GetWatchlistLots/GetWatchlistLotsQuery.cs
src/Auctionify.Application/Features/Users/Queries/GetWatchlistLots/GetWatchlistLotsResponse.cs
tests/Auctionify.UnitTests/EntitiesSeeding.cs
tests/Auctionify.UnitTests/GetAllLotsTests/GetAllLotsTests.cs
tests/Auctionify.UnitTests/GetWatshlistLotsTests/GetWatchlistLotsQueryHandlerTests.cs

[NL-41 View watchlist (buyer)](https://jjbcapital.atlassian.net/browse/NL-41)
Implement watchlist section for buyer in buyer's dashboard and improving the removal of lot from watchlist by developing a modal component for buyer's confirmation. Implemented the wishlist page as well.
Implemented all necessary features in FE and BE. Buyers (if authorized) can see their lots in wishlists by clicking the dashboard or wishlist in header (if not authorized they will be redirected to login page). The wishlist section has 5 lots per row displayed in grid. The confirmation of removal from wishlist is implemented for all pages where it is needed and used.
Dashboard view: Five lots which were added recently to buyer's wishlist.
The wishlist page (can be accessed either via wishlist in header or show …

[41] - View watchlist (buyer)

---

src/Auctionify.API/ClientApp/src/app/components/buyer/wishlist/wishlist.component.scss
src/Auctionify.API/ClientApp/src/app/components/general/home/auction/auction.component.html
src/Auctionify.API/ClientApp/src/app/components/general/home/auction/auction.component.scss

Fixes in Wishlist Page and Auction home page (buyer pages)

FE fixes in dev

---

src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.ts
src/Auctionify.API/ClientApp/src/app/components/buyer/wishlist/wishlist.component.ts
src/Auctionify.API/ClientApp/src/app/components/general/add-bid/add-bid.component.html
src/Auctionify.API/ClientApp/src/app/components/general/add-bid/add-bid.component.ts
src/Auctionify.API/ClientApp/src/app/components/general/home/auction/auction.component.ts
src/Auctionify.API/ClientApp/src/app/components/general/lot-profile/lot-profile.component.ts
src/Auctionify.API/ClientApp/src/app/components/general/profile/update-user-profile/update-user-profile.component.html
src/Auctionify.API/ClientApp/src/app/components/general/remove-from-watchlist/remove-from-watchlist.component.html
src/Auctionify.API/ClientApp/src/app/components/general/remove-from-watchlist/remove-from-watchlist.component.scss
src/Auctionify.API/ClientApp/src/app/components/general/remove-from-watchlist/remove-from-watchlist.component.ts
src/Auctionify.API/ClientApp/src/app/components/general/withdraw-bid/withdraw-bid.component.html
src/Auctionify.API/ClientApp/src/app/components/seller/create-lot/create-lot.component.ts
src/Auctionify.API/ClientApp/src/app/layout/header/header.component.ts

[NL-153 Update placeholders for name and surname](https://jjbcapital.atlassian.net/browse/NL-153)
[NL-154 Page is not refreshed after user logout](https://jjbcapital.atlassian.net/browse/NL-154)
[NL-156 Use "wishlist" instead of "watchlist" in the whole application](https://jjbcapital.atlassian.net/browse/NL-156)
[NL-157 Change button background for Confirm button](https://jjbcapital.atlassian.net/browse/NL-157)
The goal of these tickets is to fix the specified Front End fixes.
All issues and bugs were solved.
Auctionify.API.ClientApp
_Build_
_Unit Tests_
For more information about test results please refer to generated test report in the build

[153], [154], [156], [157] fixes (bugfix tickets)

---

src/Auctionify.Infrastructure/Migrations/20240111103755_RateTableTypoFix.Designer.cs
src/Auctionify.Infrastructure/Migrations/20240111103755_RateTableTypoFix.cs
src/Auctionify.Infrastructure/Migrations/20240115210732_ConversationTableCreateAndChatTableFixes.Designer.cs
src/Auctionify.Infrastructure/Migrations/20240115210732_ConversationTableCreateAndChatTableFixes.cs

This reverts commit 11c036b233606baf3ed50b75d596e6c5f7458d6a.

Revert "[152] - merge dev, and migration fixes (syncing and fixing dev)"

---

src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.html
src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.scss
src/Auctionify.API/ClientApp/src/app/components/general/profile/change-password/change-password.component.html
src/Auctionify.API/ClientApp/src/app/components/general/profile/profile-navbar/profile-navbar.component.ts
src/Auctionify.API/ClientApp/src/app/components/general/profile/update-user-profile/update-user-profile.component.html
src/Auctionify.API/ClientApp/src/app/components/general/profile/user-profile/user-profile.component.html
src/Auctionify.API/ClientApp/src/app/components/general/profile/user-profile/user-profile.component.scss
src/Auctionify.API/ClientApp/src/app/components/general/rate/feedback/feedback.component.html
src/Auctionify.API/ClientApp/src/app/components/general/rate/feedback/feedback.component.scss
src/Auctionify.API/ClientApp/src/app/components/general/rate/rating/rating.component.html
src/Auctionify.API/ClientApp/src/app/components/general/rate/rating/rating.component.scss
src/Auctionify.API/ClientApp/src/app/components/seller/dashboard/dashboard.component.html
src/Auctionify.API/ClientApp/src/app/components/seller/dashboard/dashboard.component.scss
src/Auctionify.API/ClientApp/src/app/layout/header/header.component.html
src/Auctionify.API/ClientApp/src/app/layout/header/header.component.scss
src/Auctionify.API/ClientApp/src/app/layout/header/header.component.ts
src/Auctionify.API/ClientApp/src/app/layout/navbar-seller/navbar-seller.component.html
src/Auctionify.API/ClientApp/src/app/layout/navbar-seller/navbar-seller.component.ts
src/Auctionify.API/ClientApp/src/app/layout/search/search.component.html
src/Auctionify.API/ClientApp/src/app/layout/search/search.component.scss
src/Auctionify.API/ClientApp/src/app/layout/search/search.component.ts
src/Auctionify.API/ClientApp/src/app/ui-elements/average-rating-item/average-rating-item.component.html
src/Auctionify.API/ClientApp/src/app/ui-elements/average-rating-item/average-rating-item.component.scss
src/Auctionify.API/ClientApp/src/app/ui-elements/average-rating-item/average-rating-item.component.spec.ts
src/Auctionify.API/ClientApp/src/app/ui-elements/average-rating-item/average-rating-item.component.ts
src/Auctionify.API/ClientApp/src/app/ui-elements/choice-popup/choice-popup.component.html
src/Auctionify.API/ClientApp/src/app/ui-elements/lot-item/lot-item.component.scss
src/Auctionify.API/ClientApp/src/app/ui-elements/rate-item/rate-item.component.html
src/Auctionify.API/ClientApp/src/app/ui-elements/rate-item/rate-item.component.scss

Where
[NL-160 Update search placeholder text](https://jjbcapital.atlassian.net/browse/NL-160)
[NL-159 Make tabs Wishlist and Dashboard visible only for logged in users](https://jjbcapital.atlassian.net/browse/NL-159)
[NL-167 Fix rating stars on seller dashboard](https://jjbcapital.atlassian.net/browse/NL-167)
What
Bug fixes
Affected Area
Auctionify.API.ClientApp
PR Checklist
Build
Build Succeeded
Unit Tests
[x] All 84 Tests Passed, 0 Ignored, 0 Failed

[159, 160, 167] Bug fixes

---

src/Auctionify.API/ClientApp/src/app/api-authorization/register/register.component.ts
src/Auctionify.API/ClientApp/src/app/components/general/chat/chat-item/chat-item.component.html
src/Auctionify.API/ClientApp/src/app/components/general/chat/chat-item/chat-item.component.scss
src/Auctionify.API/ClientApp/src/app/components/general/chat/conversation-window/conversation-window.component.html
src/Auctionify.API/ClientApp/src/app/components/general/chat/conversation-window/conversation-window.component.scss
src/Auctionify.API/ClientApp/src/app/components/general/chat/conversation-window/conversation-window.component.ts
src/Auctionify.API/ClientApp/src/app/components/general/lot-profile/lot-profile.component.html
src/Auctionify.API/ClientApp/src/app/components/general/lot-profile/lot-profile.component.ts
src/Auctionify.API/ClientApp/src/app/web-api-client.ts
src/Auctionify.API/Program.cs
src/Auctionify.Application/Common/Options/AppUrlOptions.cs
src/Auctionify.Application/ConfigureServices.cs
src/Auctionify.Application/Features/Chats/Commands/CreateChatMessage/CreateChatMessageCommand.cs
src/Auctionify.Application/Features/Chats/Queries/GetAllUserConversations/GetAllUserConversationsQuery.cs
src/Auctionify.Application/Features/Lots/Queries/GetAll/GetAllLotsQuery.cs
src/Auctionify.Application/Features/Lots/Queries/GetAllByLocation/GetAllLotsByLocationQuery.cs
src/Auctionify.Application/Features/Lots/Queries/GetAllByName/GetAllLotsByNameQuery.cs
src/Auctionify.Application/Features/Lots/Queries/GetByIdForBuyer/GetByIdForBuyerLotQuery.cs
src/Auctionify.Application/Features/Lots/Queries/GetByIdForBuyer/GetByIdForBuyerLotResponse.cs
src/Auctionify.Application/Features/Lots/Queries/GetByIdForSeller/GetByIdForSellerLotQuery.cs
src/Auctionify.Application/Features/Lots/Queries/GetByIdForSeller/GetByIdForSellerLotResponse.cs
src/Auctionify.Application/Scheduler/JobSchedulerService.cs
src/Auctionify.Application/Scheduler/Jobs/FinishLotJob.cs
src/Auctionify.Application/Scheduler/Jobs/GlobalLotsJob.cs
src/Auctionify.Infrastructure/ConfigureServices.cs
tests/Auctionify.UnitTests/CreateChatMessageTests/CreateChatMessageCommandHandlerTests.cs

[NL-179 Sign Up flow - unclear error message](https://jjbcapital.atlassian.net/browse/NL-179)
[NL-182 Add lot profile link in first message sent from seller (automatic message)](https://jjbcapital.atlassian.net/browse/NL-182)
[NL-180 View lot profile (buyer) - disable 'Place a bid" button in case the lot is not active](https://jjbcapital.atlassian.net/browse/NL-180)
[NL-181 Conversations are not sorted after message sent/received](https://jjbcapital.atlassian.net/browse/NL-181)
[NL-178 Add a time display for sent messages](https://jjbcapital.atlassian.net/browse/NL-178)
[NL-185 Inspect the search behavior (if it really searches all available lots for buyer)](https://jjbcapital.atlassian.net/browse/NL-185)
[NL-184 Going to seller profile through lot …

[179, 182, 180, 181, 178, 185, 184] bug fixes

---

src/Auctionify.API/ClientApp/src/app/api-authorization/authorize.service.ts
src/Auctionify.API/ClientApp/src/app/api-authorization/register/register.component.html
src/Auctionify.API/ClientApp/src/app/api-authorization/register/register.component.scss
src/Auctionify.API/ClientApp/src/app/api-authorization/register/register.component.ts
src/Auctionify.API/ClientApp/src/app/components/general/profile/update-user-profile/update-user-profile.component.html
src/Auctionify.API/ClientApp/src/app/web-api-client.ts
src/Auctionify.API/Controllers/LotsController.cs
src/Auctionify.Application/Common/Models/Account/RegisterViewModel.cs
src/Auctionify.Infrastructure/Identity/IdentityService.cs

[176] - Account creation flow fix](https://jjbcapital.atlassian.net/browse/NL-176)
First and last name fields added in front end signup page
First and last name fields added in front end signup page
Auctionify.API.ClientApp
Auctionify.Infrastructure
_Build_
_Unit Tests_

[176] Account creation flow fix
